GET http://localhost:4004/employee/personaldetails HTTP/1.1

###Get Employee full details
GET http://localhost:4004/employee/personaldetails?$expand=Address,Department HTTP/1.1
###post details
POST   http://localhost:4004/employee/personaldetails HTTP/1.1
Content-Type: application/json

  {
      "fName": "John",
      "lName": "Doe",
      "gender": "Male",
      "DOB": "1990-02-01",
      "contractStarted": "2012-03-11",
      "email": "JohnDoe1@gmail.com",
      "phone": "8512543279"
    }
###delete details
DELETE http://localhost:4004/employee/personaldetails/2239b1c7-acb3-42d1-b8af-8fd608446f92 HTTP/1.1

